# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sly/technical-test-SlyLou/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sly/technical-test-SlyLou

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sly/technical-test-SlyLou/CMakeFiles /home/sly/technical-test-SlyLou/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sly/technical-test-SlyLou/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named drawCube

# Build rule for target.
drawCube: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drawCube
.PHONY : drawCube

# fast build rule for target.
drawCube/fast:
	$(MAKE) -f CMakeFiles/drawCube.dir/build.make CMakeFiles/drawCube.dir/build
.PHONY : drawCube/fast

#=============================================================================
# Target rules for targets named squaresInRect

# Build rule for target.
squaresInRect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 squaresInRect
.PHONY : squaresInRect

# fast build rule for target.
squaresInRect/fast:
	$(MAKE) -f CMakeFiles/squaresInRect.dir/build.make CMakeFiles/squaresInRect.dir/build
.PHONY : squaresInRect/fast

#=============================================================================
# Target rules for targets named fight

# Build rule for target.
fight: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fight
.PHONY : fight

# fast build rule for target.
fight/fast:
	$(MAKE) -f CMakeFiles/fight.dir/build.make CMakeFiles/fight.dir/build
.PHONY : fight/fast

drawCube.o: drawCube.cpp.o

.PHONY : drawCube.o

# target to build an object file
drawCube.cpp.o:
	$(MAKE) -f CMakeFiles/drawCube.dir/build.make CMakeFiles/drawCube.dir/drawCube.cpp.o
.PHONY : drawCube.cpp.o

drawCube.i: drawCube.cpp.i

.PHONY : drawCube.i

# target to preprocess a source file
drawCube.cpp.i:
	$(MAKE) -f CMakeFiles/drawCube.dir/build.make CMakeFiles/drawCube.dir/drawCube.cpp.i
.PHONY : drawCube.cpp.i

drawCube.s: drawCube.cpp.s

.PHONY : drawCube.s

# target to generate assembly for a file
drawCube.cpp.s:
	$(MAKE) -f CMakeFiles/drawCube.dir/build.make CMakeFiles/drawCube.dir/drawCube.cpp.s
.PHONY : drawCube.cpp.s

fight.o: fight.cpp.o

.PHONY : fight.o

# target to build an object file
fight.cpp.o:
	$(MAKE) -f CMakeFiles/fight.dir/build.make CMakeFiles/fight.dir/fight.cpp.o
.PHONY : fight.cpp.o

fight.i: fight.cpp.i

.PHONY : fight.i

# target to preprocess a source file
fight.cpp.i:
	$(MAKE) -f CMakeFiles/fight.dir/build.make CMakeFiles/fight.dir/fight.cpp.i
.PHONY : fight.cpp.i

fight.s: fight.cpp.s

.PHONY : fight.s

# target to generate assembly for a file
fight.cpp.s:
	$(MAKE) -f CMakeFiles/fight.dir/build.make CMakeFiles/fight.dir/fight.cpp.s
.PHONY : fight.cpp.s

squaresInRect.o: squaresInRect.cpp.o

.PHONY : squaresInRect.o

# target to build an object file
squaresInRect.cpp.o:
	$(MAKE) -f CMakeFiles/squaresInRect.dir/build.make CMakeFiles/squaresInRect.dir/squaresInRect.cpp.o
.PHONY : squaresInRect.cpp.o

squaresInRect.i: squaresInRect.cpp.i

.PHONY : squaresInRect.i

# target to preprocess a source file
squaresInRect.cpp.i:
	$(MAKE) -f CMakeFiles/squaresInRect.dir/build.make CMakeFiles/squaresInRect.dir/squaresInRect.cpp.i
.PHONY : squaresInRect.cpp.i

squaresInRect.s: squaresInRect.cpp.s

.PHONY : squaresInRect.s

# target to generate assembly for a file
squaresInRect.cpp.s:
	$(MAKE) -f CMakeFiles/squaresInRect.dir/build.make CMakeFiles/squaresInRect.dir/squaresInRect.cpp.s
.PHONY : squaresInRect.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... drawCube"
	@echo "... squaresInRect"
	@echo "... fight"
	@echo "... drawCube.o"
	@echo "... drawCube.i"
	@echo "... drawCube.s"
	@echo "... fight.o"
	@echo "... fight.i"
	@echo "... fight.s"
	@echo "... squaresInRect.o"
	@echo "... squaresInRect.i"
	@echo "... squaresInRect.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

